-- Add sample prayer times for Algester mosque for testing
INSERT INTO public.prayer_times (
  mosque_id, 
  date, 
  fajr_adhan, fajr_iqamah,
  dhuhr_adhan, dhuhr_iqamah,
  asr_adhan, asr_iqamah,
  maghrib_adhan, maghrib_iqamah,
  isha_adhan, isha_iqamah,
  jumah_times,
  source_url,
  parsing_notes,
  is_current,
  admin_review_required,
  extraction_confidence
) VALUES (
  'ChIJY_gEEp9FkWsRzT1BIPP_bJM',
  CURRENT_DATE,
  '05:00', '05:15',
  '12:15', '12:30', 
  '16:00', '16:15',
  '17:30', '17:35',
  '19:00', '19:15',
  '["12:30", "13:15"]'::jsonb,
  'https://www.isoa.com.au/',
  'Manual entry - website requires JavaScript rendering for dynamic content',
  true,
  true,
  30
) ON CONFLICT (mosque_id, date) DO UPDATE SET
  fajr_adhan = EXCLUDED.fajr_adhan,
  fajr_iqamah = EXCLUDED.fajr_iqamah,
  dhuhr_adhan = EXCLUDED.dhuhr_adhan,
  dhuhr_iqamah = EXCLUDED.dhuhr_iqamah,
  asr_adhan = EXCLUDED.asr_adhan,
  asr_iqamah = EXCLUDED.asr_iqamah,
  maghrib_adhan = EXCLUDED.maghrib_adhan,
  maghrib_iqamah = EXCLUDED.maghrib_iqamah,
  isha_adhan = EXCLUDED.isha_adhan,
  isha_iqamah = EXCLUDED.isha_iqamah,
  jumah_times = EXCLUDED.jumah_times,
  parsing_notes = EXCLUDED.parsing_notes,
  admin_review_required = EXCLUDED.admin_review_required,
  extraction_confidence = EXCLUDED.extraction_confidence;